name: gaff
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  #for storing image to local storage
  gallery_saver: ^2.3.2

  #for signin auth feature
  emoji_picker_flutter: ^1.6.1
  ficonsax: ^0.0.3
  firebase_auth: ^4.7.2

  #for implementing firebase
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

  #for google signin feature
  flutter_notification_channel: ^2.0.0
  google_sign_in: ^6.1.4

  #for picking profile picture
  http: ^0.13.3
  image_picker: ^1.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon 2.png"
  min_sdk_android: 21 
  remove_alpha_ios: true


  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: SKATERDUDES
      fonts:
        - asset: fonts\SKATERDUDES.ttf

  
    - family: Avenir
      fonts:
        - asset: fonts\Avenir Light.ttf
          weight: 400
        - asset: fonts\Avenir Regular.ttf
          weight: 500
        - asset: fonts\Avenir Book.ttf
          weight: 600
        - asset: fonts\Avenir Black.ttf
          weight: 700
        - asset: fonts\Avenir Heavy.ttf
          weight: 800
 
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
